# Files for Dash

In [1]:
import pandas as pd
import numpy as np
import plotly
import plotly.graph_objs as go

%matplotlib inline

pd.set_option('display.max_columns', 500)

In [53]:
df = (pd.read_csv('data/rand.csv', parse_dates = ['date'])
        .drop(columns = 'Unnamed: 0', axis = 1))

df = (df.copy()
        .loc[df['amount']<0]
        .set_index('date')
        .resample('D').agg({'amount':'sum', 'bal':'last'})
        .replace(np.nan, method = 'ffill')
        .reset_index()
        .assign(cumulative_annual = lambda x: x.groupby(x['date'].dt.year)['amount'].cumsum(),
                cumulative_month = lambda x: x.groupby(x['date'].dt.to_period('M'))['amount'].cumsum(),
                month = lambda x: x['date'].dt.to_period('M'), 
                day = lambda x: x['date'].dt.day))
df

,date,amount,bal,cumulative_annual,cumulative_month,month,day
0,2017-01-29,-134.90,761.50,-134.90,-134.90,2017-01,29
1,2017-01-30,-476.00,695.50,-610.90,-610.90,2017-01,30
2,2017-01-31,-625.52,69.98,-1236.42,-1236.42,2017-01,31
3,2017-02-01,-63.23,42.75,-1299.65,-63.23,2017-02,1
4,2017-02-02,-4.50,538.25,-1304.15,-67.73,2017-02,2
5,2017-02-03,-31.40,506.85,-1335.55,-99.13,2017-02,3
6,2017-02-04,-85.11,421.74,-1420.66,-184.24,2017-02,4
7,2017-02-05,0.00,421.74,-1420.66,-184.24,2017-02,5
8,2017-02-06,-25.85,395.89,-1446.51,-210.09,2017-02,6
9,2017-02-07,-8.00,387.89,-1454.51,-218.09,2017-02,7
10,2017-02-08,-63.00,324.89,-1517.51,-281.09,2017-02,8
11,2017-02-09,-52.14,272.75,-1569.65,-333.23,2017-02,9
12,2017-02-10,-7.80,264.95,-1577.45,-341.03,2017-02,10
13,2017-02-11,-12.39,252.56,-1589.84,-353.42,2017-02,11
14,2017-02-12,0.00,252.56,-1589.84,-353.42,2017-02,12
15,2017-02-13,-25.85,226.71,-1615.69,-379.27,2017-02,13
16,2017-02-14,-580.04,76.67,-2195.73,-959.31,2017-02,14
17,2017-02-15,-57.04,19.63,-2252.77,-1016.35,2017-02,15
18,2017-02-16,-131.29,166.25,-2384.06,-1147.64,2017-02,16
19,2017-02-17,-7.44,158.81,-2391.50,-1155.08,2017-02,17
20,2017-02-18,-11.70,147.11,-2403.20,-1166.78,2017-02,18
21,2017-02-19,0.00,147.11,-2403.20,-1166.78,2017-02,19
22,2017-02-20,-25.85,321.26,-2429.05,-1192.63,2017-02,20
23,2017-02-21,-604.58,-283.32,-3033.63,-1797.21,2017-02,21
24,2017-02-22,-79.59,137.09,-3113.22,-1876.80,2017-02,22
25,2017-02-23,-68.00,169.09,-3181.22,-1944.80,2017-02,23
26,2017-02-24,-32.60,136.49,-3213.82,-1977.40,2017-02,24
27,2017-02-25,-39.69,196.80,-3253.51,-2017.09,2017-02,25
28,2017-02-26,0.00,196.80,-3253.51,-2017.09,2017-02,26
29,2017-02-27,-435.85,270.95,-3689.36,-2452.94,2017-02,27
...,...,...,...,...,...,...,...
807,2019-04-16,-249.39,293.65,-23011.46,-2147.62,2019-04,16
808,2019-04-17,-179.43,114.22,-23190.89,-2327.05,2019-04,17
809,2019-04-18,-120.91,93.31,-23311.80,-2447.96,2019-04,18
810,2019-04-19,-9.00,84.31,-23320.80,-2456.96,2019-04,19
811,2019-04-20,0.00,84.31,-23320.80,-2456.96,2019-04,20
812,2019-04-21,0.00,84.31,-23320.80,-2456.96,2019-04,21
813,2019-04-22,0.00,84.31,-23320.80,-2456.96,2019-04,22
814,2019-04-23,-13.50,170.81,-23334.30,-2470.46,2019-04,23
815,2019-04-24,-61.09,109.72,-23395.39,-2531.55,2019-04,24
816,2019-04-25,-862.41,2883.88,-24257.80,-3393.96,2019-04,25
817,2019-04-26,-189.70,421.18,-24447.50,-3583.66,2019-04,26
818,2019-04-27,-41.18,380.00,-24488.68,-3624.84,2019-04,27
819,2019-04-28,0.00,380.00,-24488.68,-3624.84,2019-04,28
820,2019-04-29,0.00,380.00,-24488.68,-3624.84,2019-04,29
821,2019-04-30,-121.11,258.89,-24609.79,-3745.95,2019-04,30
822,2019-05-01,-259.20,225.69,-24868.99,-259.20,2019-05,1
823,2019-05-02,-44.39,181.30,-24913.38,-303.59,2019-05,2
824,2019-05-03,-82.49,298.81,-24995.87,-386.08,2019-05,3
825,2019-05-04,-182.76,116.05,-25178.63,-568.84,2019-05,4
826,2019-05-05,-20.00,96.05,-25198.63,-588.84,2019-05,5
827,2019-05-06,0.00,96.05,-25198.63,-588.84,2019-05,6
828,2019-05-07,-23.99,372.06,-25222.62,-612.83,2019-05,7
829,2019-05-08,-36.87,335.19,-25259.49,-649.70,2019-05,8
830,2019-05-09,-977.83,854.10,-26237.32,-1627.53,2019-05,9
831,2019-05-10,-62.55,791.55,-26299.87,-1690.08,2019-05,10
832,2019-05-11,-73.20,718.35,-26373.07,-1763.28,2019-05,11
833,2019-05-12,0.00,718.35,-26373.07,-1763.28,2019-05,12
834,2019-05-13,-12.50,705.85,-26385.57,-1775.78,2019-05,13
835,2019-05-14,-54.69,651.16,-26440.26,-1830.47,2019-05,14
836,2019-05-15,-70.30,580.86,-26510.56,-1900.77,2019-05,15

In [57]:
report = (df.pivot_table(values = 'cumulative_month', index = 'day', columns = 'month', aggfunc = 'sum')
            .assign(average_past_12_months = lambda x: x[x.columns[-12:]].mean(axis=1))
            .multiply(-1))

report.columns = report.columns.astype('str')
report.head()

month,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,average_past_12_months
day,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,NaN,63.23,49.32,87.87,25.85,0.04,128.01,130.89,221.98,-0.00,130.03,6.99,-0.00,56.0,-0.0,-0.00,40.00,16.31,0.13,50.72,217.55,107.75,46.45,8.88,74.65,101.36,70.54,47.82,259.20,83.446667
2,NaN,67.73,97.66,87.87,73.55,0.04,128.01,190.61,275.73,25.85,141.03,33.60,410.00,56.0,-0.0,-0.00,61.75,134.55,40.13,1102.02,230.75,772.97,59.15,44.38,100.15,123.60,78.72,239.42,303.59,269.119167
3,NaN,99.13,282.16,173.72,356.29,10.51,133.01,190.61,275.73,460.72,214.33,33.60,458.97,66.0,-0.0,120.00,99.55,134.55,255.51,1184.06,290.74,808.71,133.15,84.38,1141.27,223.17,99.20,309.71,386.08,420.877500
4,NaN,184.24,289.65,557.27,374.59,10.51,551.01,236.46,280.73,845.64,263.73,59.45,929.42,66.0,-0.0,208.52,418.28,134.55,311.66,1255.74,318.94,5722.74,193.15,307.86,1503.72,232.16,157.67,358.17,568.84,922.100000
5,NaN,184.24,289.65,715.10,389.67,485.51,1569.08,236.46,526.03,913.26,263.73,330.30,1454.10,66.0,-0.0,361.72,432.98,247.85,320.08,1255.74,497.64,5762.04,233.55,479.61,1555.72,360.13,452.73,400.59,588.84,1012.876667

In [61]:
columns = ['2019-05', '2019-04', 'average_past_12_months']

report_data = report[columns]

In [62]:
# Properties
labels = ['This month to date', 'Last month', 'Average month']
colours = ['rgb(98, 29, 75)', 'rgb(61, 72, 73)', 'rgb(189,189,189)']
mode_size = [12, 8, 8]
line_size = [4, 2, 2]

# Add data 
traces = []

for i in range(len(labels)):
    traces.append(go.Scatter(x = report_data.index, 
                             y = report_data[report_data.columns[i]], 
                             name = labels[i],
                             mode = 'lines', 
                             line = dict(color = colours[i], 
                                         width = line_size[i]),
                             connectgaps=True))
    
for i in range(len(labels)):
    traces.append(go.Scatter(x= [report_data[report_data.columns[i]].idxmax()],
                             y= [report_data[report_data.columns[i]].max()],
                             hoverinfo = 'skip',
                             mode='markers',
                             marker= dict(color=colours[i], 
                                          size=mode_size[i])))

# Add layout
layout = go.Layout(xaxis = dict(showline=True,
                                showgrid=False,
                                showticklabels=True,
                                linecolor='rgb(204, 204, 204)',
                                linewidth=2,
                                ticks='outside',
                                tickcolor='rgb(204, 204, 204)',
                                tickwidth=2,
                                ticklen=5,
                                tickfont=dict(family='Arial',
                                              size=12,
                                              color='rgb(82, 82, 82)')),
                   yaxis = dict(showline=True,
                                showgrid=False,
                                zeroline=False,
                                hoverformat = '$,.2f',
                                showticklabels=True,
                                linecolor='rgb(204, 204, 204)',
                                linewidth=2,
                                ticks='outside',
                                tickcolor='rgb(204, 204, 204)',
                                tickwidth=2,
                                ticklen=5,
                                tickfont=dict(family='Arial',
                                              size=12,
                                              color='rgb(82, 82, 82)')),
                    autosize = False,
                    margin = dict(autoexpand=False, 
                                  l=100,
                                  r=100,
                                  t=100,
                                  b=100),
                   showlegend=False)

annotations = []

# Title
annotations.append(dict(xref='paper', #reference point to measure x from - 'paper' means the edges 
                        yref='paper', 
                        x=0.0, 
                        y=1.2,
                        xanchor='left', 
                        yanchor='bottom',
                        text='Spend comparison',
                        font=dict(family='Arial',
                                  size=30,
                                  color='rgb(61, 72, 73)'),
                        showarrow=False))

# Subtitle
annotations.append(dict(xref='paper', #reference point to measure x from - 'paper' means the edges 
                        yref='paper', 
                        x=0.0, 
                        y=1.1,
                        xanchor='left', 
                        yanchor='bottom',
                        text='Compare this month to your average spend.',
                        font=dict(family='Arial',
                                  size=14,
                                  color='rgb(61, 72, 73)'),
                        showarrow=False))
# Note
annotations.append(dict(xref='paper', 
                        yref='paper', 
                        x=0, 
                        y=-0.2,
                        xanchor='left',
                        yanchor='top',
                        text='Note: All data is fabricated. This project was created in 2019.',
                        font=dict(family='Arial',
                                  size=12,
                                  color='rgb(150,150,150)'),
                                  showarrow=False))

# # Line labels
for i in range(len(labels)):
    annotations.append(dict(xref='paper', 
                            x=0.95, 
                            y=report_data[report_data.columns[i]].max(),
                            xanchor='left', 
                            yanchor='middle',
                            text='${0:,.2f}'.format(report_data[report_data.columns[i]].max()),
                            font=dict(family='Arial',
                                      size=16, 
                                      color = colours[i]),
                            showarrow=False))
    
for i in range(len(labels)):
    annotations.append(dict(xref='paper', 
                            x=0.95, 
                            y=report_data[report_data.columns[i]].max() + 1000,
#                             y=report_data[report_data.columns[i]].max() + (report_data.max().max() * 0.1),
                            xanchor='left', 
                            yanchor='middle',
                            text=labels[i],
                            font=dict(family='Arial',
                                      size=12, 
                                      color = colours[i]),
                            showarrow=False))

layout['annotations'] = annotations # This adds the annotations to the layout dictionary - otherwise gets a bit unwieldy

fig = go.Figure(data=traces, layout=layout)
plotly.offline.plot(fig, filename='spend-comparison.html')

'spend-comparison.html'

### Things to do
- Add titles to x and y axes
- Create Dash version where you can change the frequencies